FROM registry.access.redhat.com/ubi8/ubi:8.0 

RUN yum install -y --disableplugin=subscription-manager httpd && \
yum clean all --disableplugin=subscription-manager -y && \
echo "Hello from the httpd-parent container!" > ${DOCROOT}/index.html

ENV DOCROOT=/var/www/html

ONBUILD cp ./index.html $(DOCROOT}/

EXPOSE 80

RUN rm -rf /run/httpd && mkdir /run/httpd

USER root

CMD /user/sbin/httpd -DFOREGROUND
