FROM

LABEL io.k8s.description="httpd" \
      io.k8s.display-name="child" \
      io.openshift.expose-services="8080:http" \
      io.openshift.tags="child"

RUN sed -i "s/Listen 80/Listen 8080/g" /etc/httpd/conf/httpd.conf
RUN sed -i "s/#ServerName www.example.com:80/ServerName 0.0.0.0:8080/g" /etc/httpd/conf/httpd.conf

RUN chgrp -R 0 /www/run/httpd /www/log/httpd && \
    chmod -R g=u /www/run/httpd /www/log/httpd

USER 1001

EXPOSE 8080

