FROM registry.access.redhat.com/ubi8/ubi:8.0

ENV DOCROOT=/var/www/html

RUN yum install -y httpd && yum clean all -y && echo "Hellloooo" > ${DOCROOT}/index.html

EXPOSE 80

ONBUILD cp ./src/index.html ${DOCROOT}/

RUN rm -r /run/httpd/ && mkdir /run/httpd

CMD user/sbin/httpd -DFOREGROUND
